engines:
  duplication:
    enabled: false
    config:
      languages:
      - php
  fixme:
    enabled: false
  phpmd:
    enabled: false
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR2"
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/*
