---
build: false
checks:
  php:
    code_rating: true
    duplication: true
filter:
  excluded_paths:
    - tests/
tools:
  php_analyzer: true
  php_changetracking: true
  php_code_coverage: true
  php_code_sniffer: true
  php_cpd: true
  php_cs_fixer: true
  php_loc: true
  php_mess_detector: true
  php_pdepend: true
  php_sim: true
  sensiolabs_security_checker: true
