sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi

before_script:
  - composer require satooshi/php-coveralls:1.* -n
  - composer install -n

script:
  - vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - vendor/bin/coveralls --coverage_clover=clover.xml -v

notifications:
  email: false
