sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - composer require satooshi/php-coveralls:1.* -n

install:
  - composer install -n

script:
  - vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - php vendor/bin/coveralls --coverage_clover=clover.xml -v

notifications:
  email: false
