language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi

install:
  - composer require satooshi/php-coveralls:1.* -n
  - composer install -n

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - vendor/bin/coveralls -v

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3aa436d2e9c3c113cc05
    on_success: always
    on_failure: always
    on_start: never
