sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi

script:
  - composer require satooshi/php-coveralls:1.* -n
  - composer install -n

after_script:
  - vendor/bin/phpunit --coverage-clover clover.xml
  - vendor/bin/coveralls --coverage_clover=clover.xml -v

notifications:
  email: false
