language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

addons:
    code_climate:
        repo_token: 5ad732eac95fbf92a391bf478b0bcf2dfe76e28535a4eb23b0c262c78d11036c

before_script:
  - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi

script:
  - composer require satooshi/php-coveralls:1.* codeclimate/php-test-reporter:@dev -n
  - composer install -n

after_script:
  - vendor/bin/phpunit --coverage-clover clover.xml
  - vendor/bin/coveralls --coverage_clover=clover.xml -v
  - vendor/bin/test-reporter -r

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3aa436d2e9c3c113cc05
    on_success: always
    on_failure: always
    on_start: never
